#!/bin/bash

# Create new key for a service.

# It will ask the user questions.

set -euo pipefail

ask() {
  echo -n "${1} (${2:-})? " >&2
  read -r ANSWER
  echo -n "${ANSWER:-${2}}"
}
has() {
  if ! command -v "$1"; then
    echo "$1 is not installed"
    exit 1
  fi
}

has ssh-agent
has git
has ssh-keygen
has ssh-copy-id
has nc

alias="$(ask "What is the name of the alias")"
do_upload="$(ask "Upload key to host (y/n. n for git servers)" 'y')"
user="$(ask "What is the name of the ssh user" "git")"
host="$(ask "What is the host name of the server" "${alias}")"

key="$HOME/.ssh/$alias/"

echo "alias=$alias up=$do_upload user=$user host=$host key=$key"

nc -zvw1 "$host" 22  || { echo "Host $host not reachable"; exit 1; }

if ! grep -sq "$alias" ~/.ssh/config; then
  cat >> ~/.ssh/config <<CONFIG
Host ${alias}
  HostName ${host}
  User ${user}
  IdentitiesOnly yes
  AddKeysToAgent yes
  IdentityFile ~/.ssh/${alias}/id_ed25519
CONFIG
  echo "Added $alias to ~/.ssh/config"
else
  echo "$alias already exists in  ~/.ssh/config"
fi

set -x

mkdir -p "$HOME/.ssh/${alias}"
ssh-keygen -t ed25519 -C "m2slattery+${alias}@gmail.com" -f "$HOME/.ssh/${alias}/id_ed25519"
sed -i "/^${host} /d" "$HOME/.ssh/known_hosts"

if [[ "$do_upload" == "y" ]]; then
  ssh-copy-id "${alias}"
fi

eval "$(ssh-agent -s)"
ssh-add "$HOME/ssh/${alias}/id_ed25519"

#TODO:
# https://gist.github.com/darrenpmeyer/e7ad217d929f87a7b7052b3282d1b24c

