#!/usr/bin/sh
#
# A hook script to verify what is about to be committed.
# Called by "git push" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

set -euo pipefail

against="$1"

# Redirect output to stderr.
exec 1>&2

# Get list of staged files
files="$(git diff --name-only --diff-filter=AM --cached "$against" --)"

# no TODO or FIXME comments.
! echo "$files" | xargs -d$'\n' -r grep 'FIXME\|TODO'

# build pre-push check
if [ -f yarn.lock ] && grep -sq pre-push package.json; then
  yarn pre-push
elif [ -f package-lock.json ] && grep -sq pre-push package.json; then
  npm run pre-push
fi
