#!/usr/bin/sh
#
# A hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

set -euo pipefail

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against="$(git hash-object -t tree /dev/null)"
fi

# Redirect output to stderr.
exec 1>&2

# If there are whitespace errors, print the offending file names and fail.
git diff-index --check --cached "$against" --

files="$(git diff --name-only --diff-filter=AM --cached "$against" --)"

# no FIXME comments.   TODOs are allow for commit, but not push.
! echo "$files" | xargs -r grep -F FIXME

# editorconfig-check
if command -v ec >/dev/null; then
  echo "$files" | xargs -r ec
else
  echo "W:$(basename "$0"): ec not in path"
  echo '  https://github.com/editorconfig-checker/editorconfig-checker'
fi

