wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [34, 36, 30, 32, 90]
    rows: [7, 10, 5, 6, 6, 90]
  refreshInterval: 2
  mods:
    clocks:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Japan: "Asia/Tokyo"
        Hawaii: "HST"
        Eastern: "US/Eastern"
        UTC: "UTC"
        France: "CET"
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 15
      sort: "chronological"
      type: "clocks"
    ports:
      title: "Local Servers"
      cmd: "wtfs"
      args: [servers]
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshInterval: 5
      type: cmdrunner
    subreddit:
      enabled: true
      numberOfPosts: 10
      position:
        top: 1
        left: 1
        width: 2
        height: 1
      updateInterval: 120
      sortOrder: new
      subreddit: 'hasura+nuxt+graphql'
    resourceusage:
      cpuCombined: true
      enabled: true
      position:
        top: 2
        left: 1
        height: 1
        width: 1
      refreshInterval: 2
      showCPU: true
      showMem: true
      showSwp: true
    weather:
      title: "Weather"
      enabled: true
      position:
        top: 2
        left: 2
        height: 1
        width: 1
      refreshInterval: 300
      type: cmdrunner
      cmd: "wtfs"
      args: [weather]
    curb:
      title: "curb"
      enabled: true
      position:
        top: 3
        left: 2
        height: 1
        width: 1
      refreshInterval: 7200
      type: cmdrunner
      cmd: "wtfs"
      args: [recycling]
    textfile:
      enabled: true
      filePath: "~/.config/wtf/config.yml"
      format: true
      position:
        top: 0
        left: 0
        height: 4
        width: 1
      refreshInterval: 30
      wrapText: false
    stopwatch:
      title: "Pomodoro"
      cmd: "wtfs"
      args: [pomodoro]
      enabled: true
      position:
        top: 3
        left: 1
        height: 1
        width: 1
      refreshInterval: 1
      type: cmdrunner
    notifications:
      title: "Desktop Notifications"
      cmd: "notifies"
      enabled: true
      tail: true
      position:
        top: 4
        left: 0
        height: 2
        width: 3
      refreshInterval: 1
      type: cmdrunner
    builds:
      title: "builds"
      cmd: "wtfs"
      args: ["builds"]
      enabled: true
      pty: true
      tail: false
      position:
        top: 0
        left: 3
        height: 1
        width: 2
      refreshInterval: 10
      type: cmdrunner
    processes:
      title: "processes"
      cmd: "wtfs"
      args: ["processes"]
      enabled: true
      tail: false
      position:
        top: 1
        left: 3
        height: 1
        width: 1
      refreshInterval: 4
      type: cmdrunner
    todos:
      title: "todos"
      cmd: "wtfs"
      args: ["todos"]
      enabled: true
      tail: false
      position:
        top: 2
        left: 3
        height: 1
        width: 2
      refreshInterval: 15
      type: cmdrunner
    gss:
      title: "git status"
      cmd: "wtfs"
      args: ["gss"]
      enabled: true
      tail: false
      position:
        top: 3
        left: 3
        height: 3
        width: 2
      refreshInterval: 5
      type: cmdrunner

