wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [34, 36, 30, 32, 90]
    rows: [7, 10, 5, 6, 6, 90]
  refreshInterval: 2
  mods:
    clocks:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Hawaii: "HST"
        Eastern: "US/Eastern"
        UTC: "UTC"
        CA: "America/Los_Angeles"
        Cork: "Europe/Dublin"
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 15
      sort: "chronological"
      type: "clocks"
    timers:
      title: "Timers"
      type: cmdrunner
      cmd: "wtfs"
      args: [timers]
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshInterval: 1
    subreddit:
      enabled: true
      numberOfPosts: 10
      position:
        top: 1
        left: 1
        width: 2
        height: 1
      updateInterval: 120
      sortOrder: new
      subreddit: 'hasura+nuxt+graphql'
    resourceusage:
      cpuCombined: true
      enabled: true
      position:
        top: 3
        left: 1
        height: 1
        width: 1
      refreshInterval: 2
      showCPU: true
      showMem: true
      showSwp: true
    personal:
      title: "Personal"
      enabled: true
      position:
        top: 2
        left: 2
        height: 1
        width: 1
      refreshInterval: 600
      type: cmdrunner
      cmd: "wtfs"
      args: [personal]
    ports:
      title: "Local Servers"
      cmd: "wtfs"
      args: [servers]
      enabled: true
      position:
        top: 0
        left: 0
        height: 3
        width: 1
      refreshInterval: 5
      type: cmdrunner
    stopwatch:
      title: "Pomodoro"
      cmd: "wtfs"
      args: [pomodoro]
      enabled: true
      position:
        top: 2
        left: 1
        height: 1
        width: 1
      refreshInterval: 1
      type: cmdrunner
    notifications:
      title: "Desktop Notifications"
      cmd: "notifies"
      enabled: true
      tail: true
      position:
        top: 4
        left: 0
        height: 2
        width: 3
      refreshInterval: 1
      type: cmdrunner
    builds:
      title: "builds"
      cmd: "wtfs"
      args: ["builds"]
      enabled: true
      tail: false
      position:
        top: 0
        left: 3
        height: 1
        width: 2
      refreshInterval: 10
      type: cmdrunner
    charges:
      title: "Charges"
      cmd: "wtfs"
      args: ["charges"]
      enabled: true
      tail: false
      position:
        top: 1
        left: 3
        height: 1
        width: 2
      refreshInterval: 1800
      type: cmdrunner
    processes:
      title: "processes"
      cmd: "wtfs"
      args: ["processes"]
      enabled: true
      tail: false
      position:
        top: 3
        left: 0
        height: 1
        width: 1
      refreshInterval: 4
      type: cmdrunner
    feedback:
      title: "Feedback"
      cmd: "wtfs"
      args: ["feedback"]
      enabled: true
      tail: false
      position:
        top: 2
        left: 3
        height: 1
        width: 2
      refreshInterval: 15
      type: cmdrunner
    gss:
      title: "git status"
      cmd: "wtfs"
      args: ["gss"]
      enabled: true
      tail: false
      position:
        top: 3
        left: 3
        height: 3
        width: 2
      refreshInterval: 5
      type: cmdrunner

