import = ["~/.config/alacritty/dracula/dracula.toml"]
shell = "/usr/bin/zsh"

[colors.primary]
background = "#121212"

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "K"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "F"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "F"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "B"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "B"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Paste"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Copy"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "C"
mode = "Vi|~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "C"
mode = "Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u0017"
key = "Back"
mods = "Control"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "ReceiveChar"
mouse = "Middle"

[[mouse.bindings]]
action = "ReceiveChar"
mouse = "Right"

[scrolling]
history = 0

[selection]
save_to_clipboard = false

[window]
startup_mode = "Fullscreen"
